/*
=============================================================
CREATE DATABASE AND SCHEMAS
============================================================
SCRIPT PURPOSE :
THIS SCRIPT CREATES A NEW DATABASE NAMED 'DATAWAREHOUSE' AFTER CHECKING IF IT ALREADY EXISTS
IF THE DATABASE EXISTS ,IT IS DROPPED AND RECREATED . ADDITIONALLY , THE SCRIPT SETS UP THREE SCHEMAS
WITHIN THE DATABASE: 'BRONZE','SILVER', AND 'GLOD'

WARNING :
RUNNING THIS SCRIPT WILL DROP THE ENTIRE 'DATAWAREHOUSE' DATABASE IF IT EXISTS.
ALL DATA IN THE DATABASE WILL BE PERMANENTLY DELETED. PROCEED WITH CAUTION
AND ENSURE YOU HAVE PROPER BACKUPS BEFORE RUNNING THIS SCRIPTS */


/*Create Database 'Datawarehouse'*/

USE MASTER;
GO

--DROP AND RECREATE THE DATAWAREHOUSE DATABASE
IF EXISTS (SELECT 1 FROM SYS.DATABASES WHERE NAME= 'WAREHOUSE')
BEGIN
     ALTER DATABASE WAREHOUSE SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
     DROP DATABASE WAREHOUSE;
END;
GO

--CREATE THE DATAWAREHOUSE DATASET
CREATE DATABASE DATAWAREHOUSE
GO

USE DATAWAREHOUSE;
GO

--CREATE SCHEMAS
CREATE SCHEMA BRONZE;
GO
CREATE SCHEMA SILVER;
GO
CREATE SCHEMA GOLD;
